services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
    volumes:
      - $PWD/caddy_conf:/etc/caddy
      - $PWD/caddy_site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      bastion_net:
        ipv4_address: 10.5.0.5

  bastion_server: 
    hostname: Bastion_Server
    restart: unless-stopped
    build: 
      context: .
      dockerfile: server
    ports:
      - "23:22"
    networks:
      bastion_net:
        ipv4_address: 10.5.0.6

  internal_server: 
    hostname: Internal_Server
    restart: unless-stopped
    build: 
      context: .
      dockerfile: server
    networks:
      bastion_net:
        ipv4_address: 10.5.0.10
      internal_net:
        ipv4_address: 10.6.0.10
  internal2_server: 
    hostname: Internal2_Server
    restart: unless-stopped
    build: 
      context: .
      dockerfile: server
    volumes:
      - internal_caddy_share:/home/admin/public_html
    command: > 
      /bin/bash -c "  
        echo 'check_command() {' >> /home/admin/.bashrc;
        echo '  if echo \\\"$$BASH_COMMAND\\\" | grep -qE \"(>.*|>>.*|\\\\|.*tee|cat.*>)\"; then' >> /home/admin/.bashrc;
        echo '    echo \"invalid command >:3c\"' >> /home/admin/.bashrc;
        echo '    exit 1' >> /home/admin/.bashrc;
        echo '  fi' >> /home/admin/.bashrc;
        echo '}' >> /home/admin/.bashrc;
        echo 'trap check_command DEBUG' >> /home/admin/.bashrc;

        cat /home/admin/.bashrc

        chmod 444 /home/admin/.bashrc &&
        chown root:root /home/admin/.bashrc     
        ls -la /home/admin/.bashrc

        /usr/sbin/sshd -D
        "
    networks:
      internal_net:
        ipv4_address: 10.6.0.11
      internal2_net:
        ipv4_address: 10.7.0.11

  caddy1:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - $PWD/internal_caddy/1/conf:/etc/caddy
      - $PWD/internal_caddy/1/site:/srv
    networks:
      internal_net:
        ipv4_address: 10.6.0.50
  caddy2:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - $PWD/internal_caddy/2/conf:/etc/caddy
      - internal_caddy_share:/srv

    command: > 
      /bin/sh -c "
        chown -R 1001:1001 /srv &&
        chmod -R g+rw /srv &&
        caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
      "
    networks:
      internal_net:
        ipv4_address: 10.6.0.51

volumes:
  caddy_data:
  caddy_config:
  internal_caddy_share:

networks:
  bastion_net: 
    driver: bridge
    ipam: 
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1
  internal_net: 
    driver: bridge
    ipam: 
      config:
        - subnet: 10.6.0.0/24
          gateway: 10.6.0.1
  internal2_net: 
    driver: bridge
    ipam: 
      config:
        - subnet: 10.7.0.0/24
          gateway: 10.7.0.1
